version: '3.8'

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    env_file: ./.env
    logging:
      driver: 'none'
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT

  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile.dev
    # for production
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
