FROM node:alpine

WORKDIR /usr/app
COPY package.json .
RUN npm install && npm cache clean --force

COPY ./base.json .
COPY ./nodemon.json .
COPY ./tsconfig.json .
COPY ./jest.config.js .
COPY ./src .
COPY ./.env .

EXPOSE ${NODE_DOCKER_PORT}
CMD ["npm", "run", "dev"]
