name: docker-api-build.yml

on:
  pull_request:
    branches:
      - main
    paths:
      - "api/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code 🛎
        uses: actions/checkout@v3

      - name: Build Docker Image 📦
        run: |-
          cd api
          docker-compose build --no-cache --force-rm

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code 🛎
        uses: actions/checkout@v3

      - name: Test Docker Image 📦
        run: |-
          cd api
          docker-compose up -d
